language: node_js
node_js:
- 10.4.0
before_install:
  - npm i -g npm@6.4.1
install:
- npm install
script:
- npm run lint
- bash scripts/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  tag: beta
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master
