# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
name: Test, Lint, Release and Publish

on:
  push:
    branches:
      - main

# https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write  # Required for OIDC
  contents: write  # Required for the release and tag creation

jobs:
  main:
    name: Release and publish Node package
    runs-on: github-hosted-static-ip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and test
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm test

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.3.0

      - name: Get latest tag
        id: get_latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 'v0.0.0'

      - name: See if version changed
        run: |
          if [[ "v${{ steps.extract_version.outputs.version }}" == "${{ steps.get_latest_tag.outputs.tag }}" ]]; then
            echo "VERSION_CHANGED=false" >> "$GITHUB_ENV"
          else
            echo "VERSION_CHANGED=true" >> "$GITHUB_ENV"
          fi

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        if: env.VERSION_CHANGED == 'true'
        with:
          tag: "v${{ steps.extract_version.outputs.version }}"

      - name: Create release
        if: env.VERSION_CHANGED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v${{ steps.extract_version.outputs.version }}'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish new version
        if: env.VERSION_CHANGED == 'true'
        env:
          NPM_CONFIG_PROVENANCE: true
        run: npm publish --access public --verbose
